### ISSUE TITLE
Split task dependent on ansible_pkg_mgr fact

### ISSUE THREAD

**Issue by flybyray** [robertdebock/ansible-role-python_pip#11]
This role has a hidden dependency on epel role,
because the default packages installed may be from external repository epel.

When a node previously configured *with epel repo disabled* is accepted in a new ansible environment,
the(your) epel role is not activating epel again.
Hence the following task using the generic `package` module will fail in EL7 cases.

https://github.com/robertdebock/ansible-role-python_pip/blob/496c0ffb1df8cf2f9cfe0590757e9054a6a49b83/tasks/main.yml#L9-L12

```yaml
- name: install python pip
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.package:
    name: "{{ python_pip_packages }}"
    state: present
- name: Yum | install python pip
  when: ansible_pkg_mgr == 'yum'
  ansible.builtin.yum:
    name: "{{ python_pip_packages }}"
    enablerepo:
      - epel
    state: present
- name: Dnf | install python pip
  when: ansible_pkg_mgr == 'dnf'
  ansible.builtin.dnf:
    name: "{{ python_pip_packages }}"
    state: present
```
