### ISSUE TITLE
python_pip role fails when behind a proxy

### ISSUE THREAD

**Issue by rohankrishnadev** [robertdebock/ansible-role-python_pip#7]
## Describe the bug
The [update pip](https://github.com/robertdebock/ansible-role-python_pip/blob/49aa81e4304a994c6fc07d7be50557cf43af4fce/tasks/main.yml#L11) task comes before [configure pip proxy](https://github.com/robertdebock/ansible-role-python_pip/blob/49aa81e4304a994c6fc07d7be50557cf43af4fce/tasks/main.yml#L23) or setting a [trusted host](https://github.com/robertdebock/ansible-role-python_pip/blob/49aa81e4304a994c6fc07d7be50557cf43af4fce/tasks/main.yml#L33) as such the role simply waits until eventually timing-out.

Installing pip doesn't fail as it relies on apt / dnf proxy configuration. Swapping the order of these tasks should fix the issue. I could send you a pull request if that's okay.

## Playbook

requirements.yml

```yaml
---
- src: robertdebock.bootstrap
- src: robertdebock.hostname
- src: robertdebock.update
- src: robertdebock.epel
- src: robertdebock.buildtools
- src: robertdebock.python_pip
```

playbook.yml

```yaml
---
- name: Configure host
  hosts: lnxdcknp01
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip

```

## Output

The playbook simply waits on the [update pip task](https://github.com/robertdebock/ansible-role-python_pip/blob/49aa81e4304a994c6fc07d7be50557cf43af4fce/tasks/main.yml#L11).

## Environment

- Control node OS: FreeBSD 12.1-RELEASE-p9
- Control node Ansible version: ansible 2.9.13
- Managed node OS: Ubuntu 20.04.1 LTS

However this issue can be reproduced in any environment that doesn't have direct access to the Internet.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
