### ISSUE TITLE
Minimum Ansible Version outdated

### ISSUE THREAD

**Issue by chronicc** [robertdebock/ansible-role-python_pip#9]
## Describe the bug

The galaxy documentation states that the role is working with Ansible >= 2.1. However the role is using the Ansible 4 fully qualified module name syntax.

This adheres to multiple of your roles. Please fix the minimum required Ansible version. If your roles were usable with Ansible 2.x on a specific role version, please add this information to the documentation.

## Playbook

**requirements.yml**
```yaml
---
- src: geerlingguy.java
  version: 1.10.0
- src: lrk.sonarqube
  version: 1.1.0
- src: robertdebock.bootstrap
  version: 5.2.9
- src: robertdebock.buildtools
  version: 3.1.4
- src: robertdebock.postgres
  version: 3.1.1
- src: robertdebock.python_pip
  version: 4.2.4
```

**Playbook**
```yaml
---
- hosts: sonarqube
  become: yes
  roles:
  - robertdebock.bootstrap
  - robertdebock.buildtools
  - robertdebock.python_pip
  - robertdebock.postgres
  - geerlingguy.java
  - lrk.sonarqube

```

## Output

```
ERROR! couldn't resolve module/action 'community.general.ini_file'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/chronicc/git/chronicc/ansible/roles/robertdebock.python_pip/tasks/main.yml': line 14, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: configure pip proxy
  ^ here
```

## Environment

- Control node OS: Ubuntu 20.04
- Control node Ansible version: 2.9.26
- Managed node OS: Ubuntu 20.04

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
